kind: Service
apiVersion: v1
metadata:
  labels:
    app: mysql
  name: mysql-service
  namespace: infra
spec:
  ports:
    - name: tcp
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
