apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        # 自定义host
        hosts {
          192.168.3.100    mirrors.aliyun.com
          192.168.3.100    ccr.ccs.tencentyun.com
          192.168.3.100    registry-1.docker.io
          192.168.3.100    auth.docker.io
          192.168.3.10     hub.docker.com
          192.168.3.100    www.modelscope.cn
          192.168.3.100    modelscope.oss-cn-beijing.aliyuncs.com
          192.168.3.100    archive.ubuntu.com
          192.168.3.100    security.ubuntu.com
          192.168.3.100    cloud.r-project.org
          192.168.3.100    deb.nodesource.com
          192.168.3.100    docker-76009.sz.gfp.tencent-cloud.com
          fallthrough
        }
        prometheus :9153
        forward . "/etc/resolv.conf"
        cache 30
        loop
        reload
        loadbalance
    }
    # oa.com结尾的域名使用此类dns代理
    oa.com:53 {
      errors
      cache 30
      hosts {
        3.3.3.3    example3.oa.com
        4.4.4.4    example4.oa.com
        fallthrough
      }
      forward . 4.4.4.4 5.5.5.5
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system

