apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: alertmanager-main
  namespace: monitoring
spec:
  # type: LoadBalancer # NodePort
  ports:
  - name: web
    port: 9093
    targetPort: web
#    nodePort: 31013
  selector:
    alertmanager: main
    app: alertmanager
