apiVersion: v1
data:
  alertmanager.yaml: Cmdsb2JhbDoKICByZXNvbHZlX3RpbWVvdXQ6IDVtCnRlbXBsYXRlczoKLSAnL2V0Yy9hbGVydG1hbmFnZXIvdGVtcGxhdGUvKi50bXBsJwpyb3V0ZToKICBncm91cF9ieTogWydhbGVydG5hbWUnLCAnY2x1c3RlcicsICdzZXJ2aWNlJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDFoCiAgcmVjZWl2ZXI6ICdudWxsJwogIHJvdXRlczoKICAtIG1hdGNoX3JlOgogICAgICBuYW1lc3BhY2U6ICIuKiIKICAgIHJlY2VpdmVyOiAnZGVmYXVsdCcKCiMg5ZGK6K2m5oqR5Yi244CC6YG/5YWN6YeN5aSN5ZGK6K2m55qE44CCCiMgaHR0cHM6Ly95dW5semhlbmcuZ2l0Ym9vay5pby9wcm9tZXRoZXVzLWJvb2svcGFydGktcHJvbWV0aGV1cy1qaS1jaHUvYWxlcnQvYWxlcnQtbWFuYWdlci1pbmhpYml0CmluaGliaXRfcnVsZXM6Ci0gc291cmNlX21hdGNoOgogICAgc2V2ZXJpdHk6ICdjcml0aWNhbCcKICB0YXJnZXRfbWF0Y2g6CiAgICBzZXZlcml0eTogJ3dhcm5pbmcnCiAgIyBBcHBseSBpbmhpYml0aW9uIGlmIHRoZSBhbGVydG5hbWUgaXMgdGhlIHNhbWUuCiAgZXF1YWw6IFsnYWxlcnRuYW1lJywgJ2NsdXN0ZXInLCAnc2VydmljZSddCnJlY2VpdmVyczoKCi0gbmFtZTogJ2RlZmF1bHQnCiAgd2ViaG9va19jb25maWdzOgogIC0gc2VuZF9yZXNvbHZlZDogdHJ1ZQogICAgdXJsOiAnaHR0cDovL3h4Lnh4Lnh4Lnh4LycKCi0gbmFtZTogJ251bGwnCg==
  
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
