apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  # type: LoadBalancer   # NodePort
  ports:
  - name: web
    port: 9090
    targetPort: web
    # nodePort: 31011
  selector:
    app: prometheus
    prometheus: k8s
